// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFb1BL6ytRL_SN6-LsJueyyy52aPlDYIo',
    appId: '1:406432228399:web:94eec6f9cedc8c9b5852da',
    messagingSenderId: '406432228399',
    projectId: 'chat-app-1bbc4',
    authDomain: 'chat-app-1bbc4.firebaseapp.com',
    storageBucket: 'chat-app-1bbc4.appspot.com',
    measurementId: 'G-G3JB2CFP8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlaX4tQKFAcxYsSnPypTe0q4ibcvUqZxQ',
    appId: '1:406432228399:android:fbb319c264c0cef95852da',
    messagingSenderId: '406432228399',
    projectId: 'chat-app-1bbc4',
    storageBucket: 'chat-app-1bbc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl236OXYNiqtvPLJdBA8FW2WmgkR6KWcc',
    appId: '1:406432228399:ios:db390c70e182b4865852da',
    messagingSenderId: '406432228399',
    projectId: 'chat-app-1bbc4',
    storageBucket: 'chat-app-1bbc4.appspot.com',
    iosClientId: '406432228399-dlmv6887l9b2ohggha3n3qsko15hfe5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
